# Generated by Django 2.2 on 2020-01-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('low_latency', models.BooleanField(default=False)),
                ('sla', models.BooleanField(default=False)),
                ('direct_connect', models.BooleanField(default=False)),
                ('cloud_apps', models.BooleanField(default=False)),
                ('mpls', models.BooleanField(default=False)),
                ('failover', models.BooleanField(default=False)),
                ('monitoring', models.BooleanField(default=False)),
                ('firewall', models.BooleanField(default=False)),
                ('bob', models.BooleanField(default=False)),
                ('third_party_mgmt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('install_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='main.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('star_rating', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login.User')),
                ('fk_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Vendor')),
            ],
        ),
    ]
