# Generated by Django 2.2 on 2020-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='national',
            new_name='cloud_only',
        ),
        migrations.AddField(
            model_name='match',
            name='hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='prem_only',
            field=models.BooleanField(default=False),
        ),
    ]
