# Generated by Django 2.2 on 2020-01-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200130_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bob',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cloud_apps',
        ),
        migrations.RemoveField(
            model_name='match',
            name='direct_connect',
        ),
        migrations.RemoveField(
            model_name='match',
            name='failover',
        ),
        migrations.RemoveField(
            model_name='match',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='match',
            name='mpls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='third_party_mgmt',
        ),
    ]
